alias infra='cd ~/infra'
alias ordersservice='cd ~/orders_service'
alias catalogservice='cd ~/catalog_service'
alias customerservice='cd ~/customerservice'
alias turnstile='cd ~/turnstile'
alias paymentservice='cd ~/payment_service'
alias cm='cd ~/competition_management'
alias entryservice='cd ~/entry_service'
alias communicationservice='cd ~/communication_service'
alias playthepools='cd ~/playthepools'
alias deployment='cd ~/deployment'
alias migrationservice='cd ~/migration_service'
alias scheduler='cd ~/scheduler'
alias offerservice='cd ~/offer_service'

alias gcall='cd && find -maxdepth 2 -type d -name .git -execdir sh -c "pwd; git stash" \;'
alias fpsetup='gcall && infra && rake setup:all'
alias warmpassenger='sudo netstat -nptel | grep nginx | awk '"'"'{print $4}'"'"' | while read addr; do curl $addr/blah &>/dev/null; echo $addr was hit; done'
